// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Member struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Project struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	ImageUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Task struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	AssigneeID  uuid.NullUUID
	Name        string
	Description sql.NullString
	Position    int32
	DueDate     sql.NullTime
	Status      sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	ClerkID   string
	Email     string
	Username  string
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workspace struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ImageUrl   sql.NullString
	InviteCode string
}
