// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	ClerkID   string
	Email     string
	Username  string
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workspace struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ImageUrl  sql.NullString
}
