// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, workspace_id, name, image_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateProjectParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	ImageUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ImageUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProjects = `-- name: GetProjects :many
SELECT id, workspace_id, name, image_url, created_at, updated_at FROM projects WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
